[versions]
comSquareupRetrofit2Retrofit = "2.9.0"
kotlinxCoroutinesAndroid = "1.8.0"
kotlinxCoroutinesCore = "1.6.2"
loggingInterceptor = "4.12.0"
#agp = "8.3.2"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.0" }
androidx-core = { module = "androidx.core:core-ktx", version = "1.13.1" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version = "2.7.7" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version = "2.7.7" }
androidx-biometric = { module = "androidx.biometric:biometric", version = "1.1.0" }
com-squareup-retrofit2-retrofit2 = { module = "com.squareup.retrofit2:retrofit", version.ref = "comSquareupRetrofit2Retrofit" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "comSquareupRetrofit2Retrofit" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
msal = { module = "com.microsoft.identity.client:msal", version = "5.3.1" }

[plugins]
android-application = { id = "com.android.application", version = "8.4.2" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version = "1.9.23" }